### PR TITLE
Do not set CC in Makefile

### PR DESCRIPTION
**Pull request by RobertCochran**
CC is _not_ for us to set! It is for the user to choose which compiler
they want. Don't act like we know better than the user!

---

As it says on the tin.

### CODE REVIEW

**Comment by jcbrockschmidt** [comment]
Would you prefer I do a rebase?

**Comment by jcbrockschmidt** [comment]
Woops. I accidently closed it.

**Comment by RobertCochran** [comment]
I actually remember that I was going to the build system in cmake for this
project, since cmake can smooth out the differences between systems (like
`libpng` vs `libpng6` to link against). I'll submit a patch for that in just a
minute.

**Comment by jcbrockschmidt** [comment]
Just so you know, the link argument `-lpng` works fine in Ubuntu. Is seems a `libpng16.so` file as well as a `libpng.so` file is create with an installation of the `libpng16-16` package from the standard repository.

**Comment by RobertCochran** [comment]
Interesting. Well, I've already gone through the effort of figuring out cmake, so we're using that. :P
It's over on #3.

**Pull request closed without merging**
